name: easychat
description: This package helps you to create a chat app easily.
version: 0.0.2
homepage: https://github.com/thruthesky/easychat

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
