name: easyuser
description: Easyuser is a package that can be used with other easy packages.
version: 0.0.3
homepage: https://github.com/thruthesky/easyuser

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter_advanced_avatar: ^1.5.0
  flutter_image_compress: ^2.0.4
  flutter:
    sdk: flutter
  image_picker: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
